In [28]:
import torch

## Track computation

In [29]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(f"- x: \n{x}")

y = x + 2
z = y * y * 2
z_mean = z.mean()

print(f"- z: \n{z}")
print(f"- z_mean: \n{z_mean}")

- x: 
tensor([1., 2., 3.], requires_grad=True)
- z: 
tensor([18., 32., 50.], grad_fn=<MulBackward0>)
- z_mean: 
33.33333206176758


In [30]:
z_mean.backward()
print(f"- Gradients of x: \n{x.grad}")

- Gradients of x: 
tensor([4.0000, 5.3333, 6.6667])


In [41]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]], requires_grad=True)

c = ((a + b) ** 2).mean()
c.backward()

print(f"- Gradients of a: \n{a.grad}")
print(f"- Gradients of b: \n{b.grad}")

- Gradients of a: 
tensor([[3., 4.],
        [5., 6.]])
- Gradients of b: 
tensor([[3., 4.],
        [5., 6.]])


## Skip gradient calculation

In [45]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]], requires_grad=True)
y_nograd = y.detach()

with torch.no_grad():
    c = ((a + b) ** 2).mean()

print(f"- Gradients of a: \n{a.grad}")
print(f"- Gradients of b: \n{b.grad}")

- Gradients of a: 
None
- Gradients of b: 
None


## Zeroing gradients

In [46]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

y = ((x + 2) ** 2 * 2).mean()
y.backward()

print("Gradients before zeroing:", x.grad)

x.grad.zero_()
print("Gradients after zeroing:", x.grad)

Gradients before zeroing: tensor([4.0000, 5.3333, 6.6667])
Gradients after zeroing: tensor([0., 0., 0.])
