In [1]:
import torch
import numpy as np

## Initialization

In [4]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
c = torch.randn(3, 3)
d = torch.zeros(2, 3)
e = torch.ones(2, 3)
f = torch.from_numpy(np.array([1, 2, 3]))

print(f"- Tensor a: \n{a}")
print(f"- Tensor b: \n{b}")
print(f"- Tensor c: \n{c}")
print(f"- Tensor d: \n{d}")
print(f"- Tensor e: \n{e}")

- Tensor a: 
tensor([1., 2., 3.])
- Tensor b: 
tensor([4., 5., 6.])
- Tensor c: 
tensor([[ 0.4751,  0.8661,  0.5484],
        [-0.5086, -0.5014, -1.2908],
        [ 1.7676,  2.2180, -0.6766]])
- Tensor d: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
- Tensor e: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Operations

In [8]:
print(f"- Addition: \n{a + b}")
print(f"- Subtraction: \n{a - b}")
print(f"- Multiplication: \n{a * b}")
print(f"- Division: \n{a / b}")
print(f"- Power: \n{a ** b}")
print(f"- Matmul: \n{torch.matmul(a, b)}")
print(f"- Matmul@: \n{a @ b}")

- Addition: 
tensor([5., 7., 9.])
- Subtraction: 
tensor([-3., -3., -3.])
- Multiplication: 
tensor([ 4., 10., 18.])
- Division: 
tensor([0.2500, 0.4000, 0.5000])
- Power: 
tensor([  1.,  32., 729.])
- Matmul: 
32.0
- Matmul@: 
32.0


## Reshaping and slicing

In [22]:
x = torch.randn(4, 4)
print(f"- x: \n{x}")

reshaped_x = x.view(2, 8)
print(f"- Reshaped x: \n{reshaped_x}")

sliced_x = x[:, 1:3]
print(f"- Sliced x: \n{sliced_x}")

added_dim = x.unsqueeze(0)
print(f"- Added dim: \n{added_dim}")

removed_dim = added_dim.squeeze(0)
print(f"- Removed dim: \n{removed_dim}")

- x: 
tensor([[-1.9399, -0.6457, -0.5635, -0.8897],
        [ 0.7518,  1.8127,  1.6863, -1.0440],
        [-0.0254, -0.7236, -0.5028, -0.4732],
        [ 0.8261, -0.5673, -0.2357, -0.4416]])
- Reshaped x: 
tensor([[-1.9399, -0.6457, -0.5635, -0.8897,  0.7518,  1.8127,  1.6863, -1.0440],
        [-0.0254, -0.7236, -0.5028, -0.4732,  0.8261, -0.5673, -0.2357, -0.4416]])
- Sliced x: 
tensor([[-0.6457, -0.5635],
        [ 1.8127,  1.6863],
        [-0.7236, -0.5028],
        [-0.5673, -0.2357]])
- Added dim: 
tensor([[[-1.9399, -0.6457, -0.5635, -0.8897],
         [ 0.7518,  1.8127,  1.6863, -1.0440],
         [-0.0254, -0.7236, -0.5028, -0.4732],
         [ 0.8261, -0.5673, -0.2357, -0.4416]]])
- Removed dim: 
tensor([[-1.9399, -0.6457, -0.5635, -0.8897],
        [ 0.7518,  1.8127,  1.6863, -1.0440],
        [-0.0254, -0.7236, -0.5028, -0.4732],
        [ 0.8261, -0.5673, -0.2357, -0.4416]])


## CPU - GPU

In [33]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"- Running on device: {device}")

x = torch.tensor([1.0, 2.0, 3.0])
x = x.to(device)
print(f"- Tensor on {device}: \n{x}")

y = torch.tensor([4.0, 5.0, 6.0]).to(device)
z = x + y
print(f"- Result on {device}: \n{z}")

z_cpu = z.to("cpu")
print(f"- Result on cpu: \n{z_cpu}")

- Running on device: cuda
- Tensor on cuda: 
tensor([1., 2., 3.], device='cuda:0')
- Result on cuda: 
tensor([5., 7., 9.], device='cuda:0')
- Result on cpu: 
tensor([5., 7., 9.])
