In [1]:
import numpy as np

https://numpy.org/

<img src="../_imgs/Numpy_Python_Cheat_Sheet.png" />

In [2]:
np.info(np)

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly

# Create array

In [3]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [4]:
print("a = \n", a, '\n')
print("b = \n", b, '\n')
print("c = \n", c, '\n')

a = 
 [1 2 3] 

b = 
 [[1.5 2.  3. ]
 [4.  5.  6. ]] 

c = 
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] 



In [5]:
a = np.array([1.0,2.0,3.0,4.0])
b = np.asarray([0.5,0.25,-0.5,1])

# Placeholders

In [6]:
np.zeros((3,3)) # zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3), dtype=np.int32) # ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.arange(10,32,5) # step from first while < second value

array([10, 15, 20, 25, 30])

In [9]:
np.linspace(0,2,9) # 9 evenly split between a and b

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.full((2,4),7) # scalar

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
np.eye(3) # identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
print(np.random.random((2,2))) # random from 0 to 1, size
print("\n")
print(np.random.normal(0, 0.1, size=(2, 4))) # mean, sd, size

[[0.43162728 0.53889189]
 [0.16730551 0.66979718]]


[[ 0.05929233  0.0168286  -0.14280825  0.04706696]
 [-0.01275098 -0.09642659  0.12251904  0.04750278]]


In [13]:
np.empty((4,2))

array([[ 0.05929233,  0.0168286 ],
       [-0.14280825,  0.04706696],
       [-0.01275098, -0.09642659],
       [ 0.12251904,  0.04750278]])

# Array arithmetic: + - * /

In [14]:
print(a)
print(b)

[1. 2. 3. 4.]
[ 0.5   0.25 -0.5   1.  ]


In [15]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[1.5  2.25 2.5  5.  ]
[0.5  1.75 3.5  3.  ]
[ 0.5  0.5 -1.5  4. ]
[ 2.  8. -6.  4.]


In [16]:
c = [(i+j) for (i,j) in zip(a,b)]
print(c)

[1.5, 2.25, 2.5, 5.0]


In [17]:
c = ((i+j) for (i,j) in zip(a,b))
print(c, "\n")

c = list(c)
print(c)

<generator object <genexpr> at 0x000001D77FD97A40> 

[1.5, 2.25, 2.5, 5.0]


In [18]:
print(c)
print(2 * c)
c = [(2 * i) for i in c]
print(c)

[1.5, 2.25, 2.5, 5.0]
[1.5, 2.25, 2.5, 5.0, 1.5, 2.25, 2.5, 5.0]
[3.0, 4.5, 5.0, 10.0]


In [19]:
a

array([1., 2., 3., 4.])

In [20]:
print(2 * a)
print(a / 2)

[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


# Array arithmetic: functions

In [21]:
print(a)
print(b)

[1. 2. 3. 4.]
[ 0.5   0.25 -0.5   1.  ]


In [22]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[1.5  2.25 2.5  5.  ]
[0.5  1.75 3.5  3.  ]
[ 0.5  0.5 -1.5  4. ]
[ 2.  8. -6.  4.]


In [23]:
np.exp(a) # e^a

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [24]:
np.sqrt(a) # sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [25]:
print(np.sin(a))
print(np.cos(a))
print(np.log(a)) # log(e)(a)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[0.         0.69314718 1.09861229 1.38629436]


In [26]:
a.dot(b) # dot product

3.5

# Save and load

save  
savez  
load  

In [27]:
a

array([1., 2., 3., 4.])

In [28]:
np.save("name_for_a", a) # .npy
np.savez('array.npz', a, b) # .npz (compressed)

In [29]:
d = np.load("name_for_a.npy")

### from files:

loadtxt  
genfromtxt  
savetxt  

In [30]:
np.savetxt("csvfile.csv", a, delimiter=',')

In [31]:
d = np.genfromtxt("csvfile.csv", delimiter=',')
d

array([1., 2., 3., 4.])

In [32]:
np.savetxt("nocomma.txt", a, delimiter=' ')

In [33]:
d = np.loadtxt("nocomma.txt")
d

array([1., 2., 3., 4.])

# Datatypes

np.int64  
np.float32  
np.complex  
np.bool  
np.object  
np.string_  
np.unicode_  

# Comparison

In [34]:
print(a)
print(b)

[1. 2. 3. 4.]
[ 0.5   0.25 -0.5   1.  ]


In [35]:
a == b

array([False, False, False, False])

In [36]:
a < 3

array([ True,  True, False, False])

In [37]:
np.array_equal(a, b)

False

# Aggregate functions

In [38]:
print(a)
print("sum = ", a.sum())
print("min = ", a.min())
print("max = ", a.max(axis = 0))
print("min = ", a.cumsum(axis = 0))
print("mean = ", a.mean())
print("std = ", np.std(a))

[1. 2. 3. 4.]
sum =  10.0
min =  1.0
max =  4.0
min =  [ 1.  3.  6. 10.]
mean =  2.5
std =  1.118033988749895


In [39]:
a = np.array([2,4,3,1])

In [40]:
a.sort(axis=0)
a

array([1, 2, 3, 4])

# Subsetting, slicing, indexing

In [41]:
a

array([1, 2, 3, 4])

In [42]:
b = np.array([(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
print(a[2])
print(b[1][2])

3
7


[start:end:step]

In [44]:
print(a[2:4]) # index 2, 3
print(a[:3]) # index 0,1,2
print(a[3:]) # index 3,..
print(a[-3:-1]) # index 3 from end to index 1 from end

[3 4]
[1 2 3]
[4]
[2 3]


In [45]:
print(b[1,1:3]) # row index 1, index 1,2
print(b[0:2,2]) # column index 2, index 0,1

[6 7]
[3 7]


In [46]:
print(b[0:2,1:3]) # row index 0,1 column index 1,2

[[2 3]
 [6 7]]


In [47]:
b[[1,2],[0,2]] # (1,0) , (2,2)

array([ 5, 11])

In [48]:
b[[1,2]][:,[1,3]] # (1,1) , (1,3) , (2,1) , (2,3)

array([[ 6,  8],
       [10, 12]])

In [49]:
b[b<5]

array([1, 2, 3, 4])

# Array manipulation

### reshape, insert, append, delete

In [50]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
print(b.T) # np.transpose(b)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [52]:
b.ravel() # flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
b.reshape(2,-1) #2dim, -1 => 6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [54]:
b.resize((2,6)) # remembers, 6 must be marked
print(b)
b.resize((3,4))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [55]:
np.append(b,[1,2,3])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3])

In [56]:
np.insert(b,2,0)

array([ 1,  2,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
np.delete(b,[2,3])

array([ 1,  2,  5,  6,  7,  8,  9, 10, 11, 12])

### combining arrays

In [58]:
a

array([1, 2, 3, 4])

In [59]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
np.concatenate((b,b), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
np.hstack((b,b))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])